name: Publish nightly build artifacts

on: workflow_dispatch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:  ["10.2.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.3
          arguments: test -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.3
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*ghidra-emotionengine.zip
          tag: "latest"
          overwrite: true
          file_glob: true
